### ISSUE TITLE
MotionDivWithFX Error

### ISSUE THREAD

**Issue by shaobsh** [remorses/installable-framer#3]
Trying to generate but getting this error now:

```
- error app/components/framer/fylo/fylo.js (10728:29) @ motion8
- error TypeError: (0 , installable_framer_dist_framer__WEBPACK_IMPORTED_MODULE_1__.withFX) is not a function
    at eval (./app/components/framer/fylo/fylo.js:11359:93)
    at (sc_client)/./app/components/framer/fylo/fylo.js (/Users/saif/Documents/GitHub/fylo/.next/server/app/page.js:7802:1)
    at __webpack_require__ (/Users/saif/Documents/GitHub/fylo/.next/server/webpack-runtime.js:33:43)
    at eval (./app/components/framer/fylo/index.js:5:66)
    at (sc_client)/./app/components/framer/fylo/index.js (/Users/saif/Documents/GitHub/fylo/.next/server/app/page.js:7813:1)
    at __webpack_require__ (/Users/saif/Documents/GitHub/fylo/.next/server/webpack-runtime.js:33:43)
    at eval (./app/components/expander.tsx:12:70)
    at (sc_client)/./app/components/expander.tsx (/Users/saif/Documents/GitHub/fylo/.next/server/app/page.js:7769:1)
    at __webpack_require__ (/Users/saif/Documents/GitHub/fylo/.next/server/webpack-runtime.js:33:43)
    at eval (./app/page.tsx:11:78)
    at (sc_client)/./app/page.tsx (/Users/saif/Documents/GitHub/fylo/.next/server/app/page.js:7846:1)
    at __webpack_require__ (/Users/saif/Documents/GitHub/fylo/.next/server/webpack-runtime.js:33:43)
  10726 | // https:https://framer.com/m/FYLO-COMPOSITION-5nyv.js@SvdQ0E7jGkV2jj2lbCzd
  10727 | var AnimatorFonts = getFonts5(Animator,);
> 10728 | var MotionDivWithFX = withFX(motion8.div,);
        |                             ^
  10729 | var NodeFonts = getFonts5(stdin_default6,);
  10730 | var SeedFonts = getFonts5(stdin_default7,);
  10731 | var cycleOrder6 = [
```

**Comment by remorses** [comment]
i need to add the withFX export

**Comment by shaobsh** [comment]
@remorses that would be great! It seems like when I use custom components from framer.supply, additional packages are needed. Is there anyway I can do this myself in a straight forward manner - so I don't have to open up an issue? What would you prefer?

**Comment by remorses** [comment]
Can you paste your component url that uses the withFX function? that would help me understand what to add to fixed-react pacakge

**Comment by shaobsh** [comment]
Following up, it seems like the applying an effect, in my case, the Appear - Slide in from Bottom, causes the with FX issue

**Comment by remorses** [comment]
Framer team doesn't care anymore about making the components work outside of Framer, not sure if continue working on this project makes sense

https://x.com/mattgperry/status/1733217980450824279?s=20

**Comment by remorses** [comment]
@shaobsh i found a way to make installable-framer work with latest components using the same framer bundle used by the official framer websites, can you try again?

**Comment by remorses** [comment]
I can confirm your component works 🎉
![Screenshot 2024-03-14 at 12 54 24](https://github.com/remorses/installable-framer/assets/31321188/6ebd7b7a-f58d-47e2-8da7-f24242044106)

**Comment by shaobsh** [comment]
@remorses Amazing! Thanks for solving the issue. Hope to see this library continue as Framer evolves. 🙏🏼
